x=int(input("Enter a number: "))
y=int(input("Enter a number: "))
z=int(input("Enter a number: "))
greatest= lambda x, y, z: max(x,max(y, z))
result=greatest(x, y, z)
print("The largest number is: ",result)